export default {
    ADD_TASK_REQUEST: 'INITADD_TASK_REQUEST',
    EDIT_TASK_REQUEST: 'INITEDIT_TASK_REQUEST',
    DELETE_TASK_REQUEST: 'INITDELETE_TASK_REQUEST',

    ADD_MEMBER_REQUEST: 'INITADD_MEMBER_REQUEST',
    EDIT_MEMBER_REQUEST: 'INITEDIT_MEMBER_REQUEST',
    DELETE_MEMBER_REQUEST: 'INITDELETE_MEMBER_REQUEST',
}